
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Itzik
 */
public class createUser extends javax.swing.JFrame {
    private DataBase db ;
    private String creator = "";
    
    /**
     * Creates new form createUser
     */
    public createUser() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void setDB(DataBase d){
        this.db = d;
    }

    public void setCreator(String name){
        this.creator = name;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_jLabel1 = new javax.swing.JLabel();
        password_jLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username_jTextField2 = new javax.swing.JTextField();
        admin_jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        create_jButton1 = new javax.swing.JButton();
        cancel_jButton1 = new javax.swing.JButton();
        confirm_password_jLabel3 = new javax.swing.JLabel();
        confirm_password_jPasswordField1 = new javax.swing.JPasswordField();
        password_jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        username_jLabel1.setText("Username:");

        password_jLabel1.setText("Password:");

        jLabel1.setText("Admin:");

        admin_jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Create New User");

        create_jButton1.setText("Create");
        create_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_jButton1ActionPerformed(evt);
            }
        });

        cancel_jButton1.setText("Cancel");
        cancel_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButton1ActionPerformed(evt);
            }
        });

        confirm_password_jLabel3.setText("Confirm Password : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username_jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username_jTextField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirm_password_jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirm_password_jPasswordField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(create_jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cancel_jButton1)
                                        .addGap(32, 32, 32))
                                    .addComponent(password_jPasswordField1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admin_jCheckBox1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_jLabel1)
                    .addComponent(username_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_jLabel1)
                    .addComponent(password_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_password_jLabel3)
                    .addComponent(confirm_password_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_jCheckBox1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_jButton1)
                    .addComponent(cancel_jButton1))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_jCheckBox1ActionPerformed

    private void create_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.username_jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be blank", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else if(!this.username_jTextField2.getText().toLowerCase().startsWith("dp")){
            JOptionPane.showMessageDialog(null, "Username must to start with 'dp'", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else if(this.password_jPasswordField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Password cannot be blank", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else if(!this.username_jTextField2.getText().substring(2).matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Username is not matched to form [dp00000]", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else if(!this.password_jPasswordField1.getText().equals(this.confirm_password_jPasswordField1.getText())){
            JOptionPane.showMessageDialog(null, "Password is not match", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else if(this.password_jPasswordField1.getText().length() < 8 ){
            JOptionPane.showMessageDialog(null, "Password must contain at lest 8 chars", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else{
            ArrayList user_data = db.searchUser(this.username_jTextField2.getText());
            if(!user_data.get(0).equals("false")){
                JOptionPane.showMessageDialog(null, "Username alredy exist", "Alert", JOptionPane.ERROR_MESSAGE);
            }
            else {
                Object temp = this.db.addNewUser(this.creator, this.username_jTextField2.getText(), this.password_jPasswordField1.getText(), this.admin_jCheckBox1.isSelected()? 1 : 0);
                if(temp instanceof Exception){
                    JOptionPane.showMessageDialog(null, "ERROR! \n "+((Exception) temp).getMessage(), "Alert", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Success!", "information", JOptionPane.INFORMATION_MESSAGE);
                }              
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_create_jButton1ActionPerformed

    private void cancel_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancel_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new createUser().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admin_jCheckBox1;
    private javax.swing.JButton cancel_jButton1;
    private javax.swing.JLabel confirm_password_jLabel3;
    private javax.swing.JPasswordField confirm_password_jPasswordField1;
    private javax.swing.JButton create_jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel password_jLabel1;
    private javax.swing.JPasswordField password_jPasswordField1;
    private javax.swing.JLabel username_jLabel1;
    private javax.swing.JTextField username_jTextField2;
    // End of variables declaration//GEN-END:variables
}
