
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Itzik
 */
public class deleteUser extends javax.swing.JFrame {
    private DataBase db ;
    private String creator = "";
    
    /**
     * Creates new form deleteUser
     */
    public deleteUser() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void setDB(DataBase d){
        this.db = d;
    }
    
    public void setCreator(String name){
        this.creator = name;
    }
    
    
    public void editable(boolean state){
        this.found_password_jLabel2.setVisible(state);
        this.found_password_jPasswordField2.setVisible(state);
        this.found_username_jLabel1.setVisible(state);
        this.found_username_jTextField1.setVisible(state);
        this.admin_jCheckBox1.setVisible(state);
        this.admin_jLabel1.setVisible(state);
        this.delete_jButton1.setVisible(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_jLabel1 = new javax.swing.JLabel();
        username_jLabel2 = new javax.swing.JLabel();
        username_jTextField1 = new javax.swing.JTextField();
        find_jButton1 = new javax.swing.JButton();
        found_username_jLabel1 = new javax.swing.JLabel();
        found_username_jTextField1 = new javax.swing.JTextField();
        found_password_jLabel2 = new javax.swing.JLabel();
        found_password_jPasswordField2 = new javax.swing.JPasswordField();
        admin_jLabel1 = new javax.swing.JLabel();
        admin_jCheckBox1 = new javax.swing.JCheckBox();
        delete_jButton1 = new javax.swing.JButton();
        cancel_jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        title_jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title_jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_jLabel1.setText("Delete User");

        username_jLabel2.setText("Username : ");

        username_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_username_jTextField1ActionPerformed(evt);
            }
        });

        find_jButton1.setText("Find");
        find_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_jButton1ActionPerformed(evt);
            }
        });

        found_username_jLabel1.setText("Username : ");

        found_username_jTextField1.setEditable(false);

        found_password_jLabel2.setText("Password : ");

        found_password_jPasswordField2.setEditable(false);

        admin_jLabel1.setText("Admin:");

        admin_jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jCheckBox1ActionPerformed(evt);
            }
        });

        delete_jButton1.setText("Delete");
        delete_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_jButton1ActionPerformed(evt);
            }
        });

        cancel_jButton2.setText("Cancel");
        cancel_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(title_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(found_password_jLabel2)
                            .addComponent(found_username_jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(found_username_jTextField1)
                            .addComponent(found_password_jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username_jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(admin_jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admin_jCheckBox1)
                                .addGap(213, 213, 213)))
                        .addComponent(find_jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_jButton2)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(find_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(username_jLabel2)
                        .addComponent(username_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(found_username_jLabel1)
                    .addComponent(found_username_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(found_password_jLabel2)
                    .addComponent(found_password_jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_jCheckBox1)
                    .addComponent(admin_jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_jButton1)
                    .addComponent(cancel_jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_username_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_username_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_username_jTextField1ActionPerformed

    private void find_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList user = this.db.searchUser(this.username_jTextField1.getText());
        if(user.get(0).equals("false")){
            JOptionPane.showMessageDialog(null, "User not found", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.found_username_jTextField1.setText(user.get(1).toString());
            this.found_password_jPasswordField2.setText(user.get(2).toString());
            if(user.get(3).toString().equals("1")){
                this.admin_jCheckBox1.setSelected(true) ;
            }
            else{
                this.admin_jCheckBox1.setSelected(false);
            }
            this.editable(true);
        }
    }//GEN-LAST:event_find_jButton1ActionPerformed

    private void admin_jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_jCheckBox1ActionPerformed

    private void delete_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_jButton1ActionPerformed
        // TODO add your handling code here:
        Object temp = this.db.deleteUser(this.creator, this.username_jTextField1.getText());
    if (temp instanceof Exception) {
      JOptionPane.showMessageDialog(null, "Delete failed \n " + ((Exception)temp).getMessage(), "Alert", 0);
    } else {
      
      JOptionPane.showMessageDialog(null, "Delete Successful!", "information", 1);
      setVisible(false);
      if (this.creator.equals(this.username_jTextField1.getText())) {
        System.exit(0);
      }
    } 
    }//GEN-LAST:event_delete_jButton1ActionPerformed

    private void cancel_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButton2ActionPerformed
        // TODO add your handling code here:
        this.editable(false);
        this.setVisible(false);
    }//GEN-LAST:event_cancel_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new deleteUser().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admin_jCheckBox1;
    private javax.swing.JLabel admin_jLabel1;
    private javax.swing.JButton cancel_jButton2;
    private javax.swing.JButton delete_jButton1;
    private javax.swing.JButton find_jButton1;
    private javax.swing.JLabel found_password_jLabel2;
    private javax.swing.JPasswordField found_password_jPasswordField2;
    private javax.swing.JLabel found_username_jLabel1;
    private javax.swing.JTextField found_username_jTextField1;
    private javax.swing.JLabel title_jLabel1;
    private javax.swing.JLabel username_jLabel2;
    private javax.swing.JTextField username_jTextField1;
    // End of variables declaration//GEN-END:variables
}
