
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Itzik
 */
public class main extends javax.swing.JFrame {

    private DataBase db;
    private storageTabs st;

    /**
     * Creates new form NewJFrame
     */
    public main() {
        initComponents();
        this.db = new DataBase();
        this.st = new storageTabs();
        this.database_jLabel5.setText("DB: " + this.db.getDbName());
        this.database_jLabel5.setBackground(Color.white);
        if (this.db.getDbName().contains("testing")) {
            this.warning_jLabel4.setText("Warning!");
        }
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.username_TF.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent fe) {
                    username_TF.selectAll();                
                }

                @Override
                public void focusLost(FocusEvent fe) {
                }
            });
        this.password_field.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent fe) {
                    password_field.selectAll();                
                }

                @Override
                public void focusLost(FocusEvent fe) {
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        warning_jLabel4 = new javax.swing.JLabel();
        database_jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_TF = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hazor Storage System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setLayout(null);

        warning_jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        warning_jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        warning_jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(warning_jLabel4);
        warning_jLabel4.setBounds(0, 340, 130, 40);

        database_jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        database_jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        database_jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(database_jLabel5);
        database_jLabel5.setBounds(0, 370, 220, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setText("Storage");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 20, 190, 56);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setText("Hazor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 0, 140, 50);

        username_TF.setText("Username");
        jPanel1.add(username_TF);
        username_TF.setBounds(60, 50, 160, 30);

        password_field.setText("jPassw");
        jPanel1.add(password_field);
        password_field.setBounds(60, 90, 160, 30);

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(login_button);
        login_button.setBounds(90, 150, 75, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The-Squadron-696x522.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        if (this.username_TF.getText().length() == 0 || this.password_field.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Username or Password can not be blank", "Alert", JOptionPane.ERROR_MESSAGE);
        } else if (!db.userAuth(this.username_TF.getText(), this.password_field.getText())) {
            JOptionPane.showMessageDialog(null, "incorrect Username or Password", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            this.st = new storageTabs();
            this.st.setDB(this.db);
            this.st.firstLoad();
            st.setAdmin(db.isAdmin(this.username_TF.getText()));
            st.setAdminButtonsVisible();
            st.setUser(this.username_TF.getText());
            st.setVisible(true);
            st.showLowQuntity();
            setVisible(false);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main nj = new main();//.setVisible(true);
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                nj.getRootPane().setDefaultButton(nj.login_button);
                nj.setLocation(dim.width / 2 - nj.getSize().width / 2, dim.height / 2 - nj.getSize().height / 2);
                nj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel database_jLabel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField username_TF;
    private javax.swing.JLabel warning_jLabel4;
    // End of variables declaration//GEN-END:variables
}
